export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/llm_reasoning.py     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs_qwen/specialized_llm_3b_qwen_base_2000_checkpoint-125/specialized_llm_3b_qwen_base_2000_checkpoint-125_num_beams_5_retrieved_2742693922251837857.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/reasoning_results_qwen     --num-workers 30     --vllm-server-host http://localhost:8264     --model-name Llama-3.3-70B-Instruct

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/llm_reasoning.py     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs_qwen/specialized_llm_3b_qwen_base_5000_checkpoint-156/specialized_llm_3b_qwen_base_5000_checkpoint-156_num_beams_5_retrieved_-2837318021217133161.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/reasoning_results_qwen     --num-workers 30     --vllm-server-host http://localhost:8264     --model-name Llama-3.3-70B-Instruct

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/llm_reasoning.py     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs_qwen/specialized_llm_3b_qwen_base_100_checkpoint-100/specialized_llm_3b_qwen_base_100_checkpoint-100_num_beams_5_retrieved_-4593082456085843523.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/reasoning_results_qwen     --num-workers 30     --vllm-server-host http://localhost:8264     --model-name Llama-3.3-70B-Instruct

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/llm_reasoning.py     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs_qwen/specialized_llm_3b_qwen_base_500_checkpoint-125/specialized_llm_3b_qwen_base_500_checkpoint-125_num_beams_5_retrieved_7193442786844031891.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/reasoning_results_qwen     --num-workers 30     --vllm-server-host http://localhost:8264     --model-name Llama-3.3-70B-Instruct

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/llm_reasoning.py     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs_qwen/specialized_llm_3b_qwen_base_10000_checkpoint-157/specialized_llm_3b_qwen_base_10000_checkpoint-157_num_beams_5_retrieved_6082511396414348243.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/reasoning_results_qwen     --num-workers 30     --vllm-server-host http://localhost:8264     --model-name Llama-3.3-70B-Instruct