export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 1     --algorithm-top-k-unknown-each-connected-node 1     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_10.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_10.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 3     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_10.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 1     --algorithm-top-k-unknown-each-connected-node 1     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 3     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 1     --algorithm-top-k-unknown-each-connected-node 1     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_1.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_1.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 3     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_1.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 1     --algorithm-top-k-unknown-each-connected-node 1     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_3.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_3.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 3     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_3.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 1     --algorithm-top-k-unknown-each-connected-node 1     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5_without_constraint.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 1     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5_without_constraint.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5

export PYTHONPATH="$(pwd)":$PYTHONPATH
python workflow/pipeline/retrieve_subgraphs.py     --algorithm-top-k-unknown-relations 3     --algorithm-top-k-unknown-each-connected-node 3     --algorithm-top-k-complete-relations 3     --input-file-path /home/namb/hoangpv4/kg_fact_checking/data/output/pseudo_subgraphs/specialized_llm_3b_base_500_checkpoint-125/specialized_llm_3b_base_500_checkpoint-125_num_beams_5_without_constraint.json     --output-folder /home/namb/hoangpv4/kg_fact_checking/data/output/retrieved_subgraphs/specialized_llm_3b_base_500_checkpoint-125     --nx-graph-path /home/namb/hoangpv4/kg_fact_checking/data/processed_factkg/dbpedia_2015_undirected_light.gpkl     --retrieval-model-path /raid/HUB_LLM/bge-large-en-v1.5