base_model: /raid/HUB_LLM/Llama-3.2-3B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: llama3
datasets:
  - path: json
    data_files:
      - /workspace/home/namb/hoangpv4/kg_fact_checking/data/train_specialized_llm/data_ready_to_train_500.jsonl
    type: chat_template
    field_messages: messages
    message_field_role: role
    message_field_content: content
    train_on_eos: turn
    
val_set_size: 0.0
output_dir: /raid/hoangpv4/models/specialized_llm_3b_base_500

sequence_len: 256
sample_packing: false
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: constant
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 5
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed: /workspace/home/namb/hoangpv4/kg_fact_checking/axolotl_config/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
  eos_token: <|eot_id|>
tokens:
  - "<entity>"
  - "</entity>"
  - "~"